//! Best-effort live completions sourced from the running Herdr server.
//!
//! Shell completion is generated by invoking `herdr` with `COMPLETE=<shell>`.
//! These helpers query the local server's socket for live identifiers (pane
//! IDs, agent targets, plugin action IDs) and return nothing when the server is
//! unreachable, the protocol is unsupported, or a request times out. They must
//! never print to stdout/stderr: completion output on stdout is consumed by the
//! shell, so any extra output would corrupt the candidate list.

use std::time::Duration;

use crate::api::client::ApiClient;
use crate::api::schema::{
    EmptyParams, Method, PaneListParams, PluginActionListParams, Request, ResponseResult,
    SuccessResponse,
};

const LIVE_COMPLETION_TIMEOUT: Duration = Duration::from_millis(500);

fn live_response(method: Method) -> Option<ResponseResult> {
    let value = ApiClient::local()
        .request_value_with_timeout(
            &Request {
                id: "cli:completion".into(),
                method,
            },
            LIVE_COMPLETION_TIMEOUT,
        )
        .ok()?;
    let response: SuccessResponse = serde_json::from_value(value).ok()?;
    Some(response.result)
}

/// Live pane IDs from the running server.
pub(crate) fn pane_ids() -> Vec<String> {
    let Some(ResponseResult::PaneList { panes }) =
        live_response(Method::PaneList(PaneListParams { workspace_id: None }))
    else {
        return Vec::new();
    };
    sorted_unique(panes.into_iter().map(|pane| pane.pane_id))
}

/// Live agent targets (terminal IDs, custom names, and detected agent labels).
pub(crate) fn agent_targets() -> Vec<String> {
    let Some(ResponseResult::AgentList { agents }) =
        live_response(Method::AgentList(EmptyParams::default()))
    else {
        return Vec::new();
    };
    let mut targets = Vec::new();
    for agent in agents {
        targets.push(agent.terminal_id);
        if let Some(name) = agent.name {
            targets.push(name);
        }
        if let Some(agent) = agent.agent {
            targets.push(agent);
        }
        if let Some(display_agent) = agent.display_agent {
            targets.push(display_agent);
        }
    }
    sorted_unique(targets.into_iter())
}

/// Live plugin action IDs from the running server.
pub(crate) fn plugin_action_ids() -> Vec<String> {
    let Some(ResponseResult::PluginActionList { actions }) =
        live_response(Method::PluginActionList(PluginActionListParams {
            plugin_id: None,
        }))
    else {
        return Vec::new();
    };
    sorted_unique(actions.into_iter().map(|action| action.action_id))
}

fn sorted_unique(values: impl Iterator<Item = String>) -> Vec<String> {
    let mut values: Vec<String> = values.collect();
    values.sort();
    values.dedup();
    values
}
